### ISSUE TITLE
length of the gaze vector

### ISSUE THREAD

**Issue by alesubbiah** [hysts/pytorch_mpiigaze_demo#32]
Hello @hysts!
Thanks so much for your help before with this! Using the other model and the other face-detector has really improved the results! Thank you!

I have updated my demo.py file to:
```
def _draw_gaze_vector(self, face: Face) -> None:
        #length = self.config.demo.gaze_visualization_length
        length = 1
       ... 
```
You mentioned the length value should be in meters. But I don't detect any change in the length of the line of the gaze the model identifies. It's still very short:
![d5e2545d-3d73-4d52-badb-6402fa7ab78b](https://user-images.githubusercontent.com/103668694/183120949-c7c09b7c-8596-4d4a-86aa-3a444f17efa2.png)

Ideally I would want it to be as long as this, at least or more:
![download-1](https://user-images.githubusercontent.com/103668694/183120727-1b4e4521-df46-4382-ba0a-1aa20e3449bf.png)
 
Do let me know if there is another way? 
Many thanks !!
Warmly, 
Ale

**Comment by hysts** [comment]
Hi, @alesubbiah 

Hmm, that's weird. It works for me.

With `demo.gaze_visualization_length = 0.05`, I got this:
![](https://user-images.githubusercontent.com/25161192/183249126-9d46d0c6-d7b1-430c-96a4-b1daca68dc6a.jpg)

and with `demo.gaze_visualization_length = 0.2`, I got this:
![](https://user-images.githubusercontent.com/25161192/183249184-d8ef85cc-ee4f-4add-89b1-9ad02d254604.jpg)

It seems you are directly modifying the code, but which code did you modify and what command did you run?
I mean, if you modified and ran `ptgaze --mode face_alignment_sfd --image image.jpg`, I think that's OK. But if you cloned this repo and modified it, then you have to run like this: `python -m ptgaze --mode face_alignment_sfd --image image.jpg`.
This is the only cause I can think of right now.

By  the way, directly modifying the code is not recommended. You can write a config file and use it to change those parameters. You can find sample config files in [this directory](https://github.com/hysts/pytorch_mpiigaze_demo/tree/master/ptgaze/data/configs).

For example, if you clone this repo, save this config file as `config.yaml`
```yaml
mode: MPIIGaze
device: cpu
model:
  name: resnet_preact
face_detector:
  mode: face_alignment_sfd
  dlib_model_path: ~/.ptgaze/dlib/shape_predictor_68_face_landmarks.dat
  mediapipe_max_num_faces: 3
  mediapipe_static_image_mode: false
gaze_estimator:
  checkpoint: ~/.ptgaze/models/mpiigaze_resnet_preact.pth
  camera_params: ptgaze/data/calib/sample_params.yaml
  use_dummy_camera_params: false
  normalized_camera_params: ptgaze/data/normalized_camera_params/mpiigaze.yaml
  normalized_camera_distance: 0.6
demo:
  use_camera: false
  display_on_screen: true
  wait_time: 1
  image_path: assets/inputs/image00.jpg
  video_path: null
  output_dir: out
  output_file_extension: avi
  head_pose_axis_length: 0.05
  gaze_visualization_length: 0.2
  show_bbox: true
  show_head_pose: false
  show_landmarks: false
  show_normalized_image: false
  show_template_model: false
```
and run
```bash
ptgaze --config config.yaml
```
then, you should get the second result above.

Would you try this?

**Comment by alesubbiah** [comment]
Hi @hysts !
Thanks so much for your help with this, and for showing me the config file! That's super helpful. 

I have copied your .yaml file, and changed the path for the image and cam params, so that it now looks like this: 

```
mode: MPIIGaze
device: cpu
model:
  name: resnet_preact
face_detector:
  mode: face_alignment_sfd
  dlib_model_path: ~/.ptgaze/dlib/shape_predictor_68_face_landmarks.dat
  mediapipe_max_num_faces: 3
  mediapipe_static_image_mode: false
gaze_estimator:
  checkpoint: ~/.ptgaze/models/mpiigaze_resnet_preact.pth
  camera_params: ptgaze/data/calib/sample_params.yaml
  use_dummy_camera_params: false
  normalized_camera_params: ptgaze/data/normalized_camera_params/mpiigaze.yaml
  normalized_camera_distance: 0.6
demo:
  use_camera: false
  display_on_screen: true
  wait_time: 1
  image_path: assets/inputs/tega.png
  video_path: null
  output_dir: out
  output_file_extension: avi
  head_pose_axis_length: 0.05
  gaze_visualization_length: 0.2
  show_bbox: true
  show_head_pose: false
  show_landmarks: false
  show_normalized_image: false
  show_template_model: false
```

I'm running this from a colab notebook, so I have saved the config.yaml file in /content/ (see screenshot with folder structure below). I have run both 
`!python -m ptgaze --config config.yaml`
and 
`!ptgaze --config config.yaml`

But I still get the same error: 
```
INFO:ptgaze.demo:[reye] pitch: -4.52, yaw: -4.99
INFO:ptgaze.demo:[leye] pitch: -6.73, yaw: -10.55
qt.qpa.xcb: could not connect to display 
qt.qpa.plugin: Could not load the Qt platform plugin "xcb" in "/usr/local/lib/python3.7/dist-packages/cv2/qt/plugins" even though it was found.
This application failed to start because no Qt platform plugin could be initialized. Reinstalling the application may fix this problem.

Available platform plugins are: xcb.
```
The code does work when I don't use a config file running both `!ptgaze... ` and `python -m ptgaze` so not sure where the issue is. 

Here is my file structure in the notebook:
<img width="431" alt="Screenshot 2022-08-08 at 11 20 14" src="https://user-images.githubusercontent.com/103668694/183396558-8c2a5bbc-2240-4d2e-a141-80fe68eba944.png">
 
When I have moved the config file, it's not able to open it, but do let me know if it should be somewhere else. 

Again thank you so, so much for your help! And for getting back to me so quickly.
Warmly, 
Ale
